--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/RepairUI
build-by-default: true
branches:
- PM4
projects:
  RepairUI:
    path: ""
    icon: icon-repairui.png
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
      - src: davidglitch04/libEco/libEco
        version: ^3.0.0
    lint:
      phpstan: false
...
